export const PREDEFINED_VARIABLES: { category: string; name: string }[] = [
  { category: 'Prestataire', name: 'prestataire_nom' },
  { category: 'Prestataire', name: 'prestataire_adresse' },
  { category: 'Prestataire', name: 'prestataire_siret' },
  { category: 'Prestataire', name: 'prestataire_tva' },
  { category: 'Client', name: 'client_prenom' },
  { category: 'Client', name: 'client_nom' },
  { category: 'Client', name: 'client_raison_sociale' },
  { category: 'Client', name: 'client_siret' },
  { category: 'Client', name: 'client_representant' },
  { category: 'Client', name: 'client_qualite' },
  { category: 'Client', name: 'client_adresse' },
  { category: 'Client', name: 'client_code_postal' },
  { category: 'Client', name: 'client_ville' },
  { category: 'Client', name: 'client_email' },
  { category: 'Client', name: 'client_telephone' },
  { category: 'Contrat', name: 'numero_contrat' },
  { category: 'Contrat', name: 'version_contrat' },
  { category: 'Contrat', name: 'date_contrat' },
  { category: 'Contrat', name: 'date_debut' },
  { category: 'Contrat', name: 'date_fin' },
  { category: 'Contrat', name: 'duree_contrat' },
  { category: 'Financier', name: 'montant_ht' },
  { category: 'Financier', name: 'montant_tva' },
  { category: 'Financier', name: 'montant_ttc' },
  { category: 'Financier', name: 'taux_tva' },
  { category: 'Financier', name: 'modalites_paiement' },
  { category: 'Financier', name: 'description_prestation' },
  { category: 'Abonnement', name: 'nom_offre' },
  { category: 'Abonnement', name: 'description_offre' },
  { category: 'Abonnement', name: 'montant_mensuel' },
  { category: 'Abonnement', name: 'duree_engagement' },
  { category: 'Abonnement', name: 'delai_resiliation' },
  { category: 'Marché public', name: 'reference_marche' },
  { category: 'Marché public', name: 'nom_marche' },
  { category: 'Marché public', name: 'pouvoir_adjudicateur' },
  { category: 'Marché public', name: 'duree_marche' },
  { category: 'Web', name: 'nom_site' },
  { category: 'Web', name: 'url_site' },
  { category: 'Signature', name: 'ville_signature' },
  { category: 'Signature', name: 'date_signature' },
];
