export const EMOJI_CATS: { icon: string; emojis: string[] }[] = [
  {
    icon: "😀",
    emojis: [
      "😀",
      "😃",
      "😄",
      "😁",
      "😆",
      "😅",
      "🤣",
      "😂",
      "🙂",
      "😊",
      "😇",
      "🥰",
      "😍",
      "🤩",
      "😘",
      "😗",
      "😚",
      "😙",
      "🥲",
      "😋",
      "😛",
      "😜",
      "🤪",
      "😝",
      "🤗",
      "🤭",
      "🤫",
      "🤔",
      "😏",
      "🥳",
    ],
  },
  {
    icon: "👋",
    emojis: [
      "👋",
      "🤚",
      "✋",
      "🖖",
      "👌",
      "🤌",
      "🤏",
      "✌️",
      "🤞",
      "🤟",
      "🤘",
      "🤙",
      "👈",
      "👉",
      "👆",
      "👇",
      "☝️",
      "👍",
      "👎",
      "✊",
      "👊",
      "🤛",
      "🤜",
      "👏",
      "🙌",
      "👐",
      "🤲",
      "🤝",
      "🙏",
      "💪",
    ],
  },
  {
    icon: "❤️",
    emojis: [
      "❤️",
      "🧡",
      "💛",
      "💚",
      "💙",
      "💜",
      "🖤",
      "🤍",
      "🤎",
      "💔",
      "❤️‍🔥",
      "❤️‍🩹",
      "❣️",
      "💕",
      "💞",
      "💓",
      "💗",
      "💖",
      "💘",
      "💝",
      "💟",
      "💌",
      "💑",
      "💏",
      "🫶",
      "🥰",
      "😍",
      "😘",
      "😻",
      "💒",
    ],
  },
  {
    icon: "🔥",
    emojis: [
      "🔥",
      "💯",
      "✨",
      "🚀",
      "💎",
      "👑",
      "🏆",
      "🥇",
      "⚡",
      "💥",
      "🌟",
      "🎯",
      "💪",
      "🙌",
      "👏",
      "🤝",
      "💰",
      "📈",
      "🧠",
      "💡",
      "🎉",
      "❤️‍🔥",
      "🦄",
      "🌈",
      "☀️",
      "🌙",
      "⭐",
      "✅",
      "❌",
      "💫",
    ],
  },
  {
    icon: "💼",
    emojis: [
      "💼",
      "💰",
      "💵",
      "💶",
      "💷",
      "🪙",
      "💳",
      "💎",
      "⚖️",
      "🏦",
      "🏢",
      "📞",
      "📱",
      "💻",
      "🖥️",
      "📧",
      "📄",
      "📊",
      "📈",
      "📉",
      "📆",
      "📋",
      "📌",
      "📎",
      "🔒",
      "🔑",
      "📁",
      "📝",
      "✂️",
      "🖊️",
    ],
  },
];

export const PRESET_COLORS = [
  "#000000",
  "#333333",
  "#555555",
  "#777777",
  "#999999",
  "#cccccc",
  "#ffffff",
  "#ef4444",
  "#f97316",
  "#eab308",
  "#22c55e",
  "#14b8a6",
  "#3b82f6",
  "#8b5cf6",
  "#ec4899",
  "#f43f5e",
  "#fb923c",
  "#fbbf24",
  "#4ade80",
  "#2dd4bf",
  "#60a5fa",
  "#a78bfa",
  "#fecdd3",
  "#fed7aa",
  "#fef08a",
  "#bbf7d0",
  "#a5f3fc",
  "#bfdbfe",
  "#ddd6fe",
  "#f1f5f9",
];

export const FONT_OPTIONS = [
  { label: "Inter", value: "Inter, sans-serif" },
  { label: "DM Sans", value: "'DM Sans', sans-serif" },
  { label: "Montserrat", value: "Montserrat, sans-serif" },
  { label: "Urbanist", value: "Urbanist, sans-serif" },
  { label: "Lexend", value: "Lexend, sans-serif" },
  { label: "Work Sans", value: "'Work Sans', sans-serif" },
  { label: "Rubik", value: "Rubik, sans-serif" },
  { label: "Karla", value: "Karla, sans-serif" },
  { label: "Archivo", value: "Archivo, sans-serif" },
  { label: "Nunito", value: "Nunito, sans-serif" },
  { label: "Poppins", value: "Poppins, sans-serif" },
  { label: "Raleway", value: "Raleway, sans-serif" },
  { label: "Outfit", value: "Outfit, sans-serif" },
  { label: "Plus Jakarta Sans", value: "'Plus Jakarta Sans', sans-serif" },
  { label: "Manrope", value: "Manrope, sans-serif" },
  { label: "Figtree", value: "Figtree, sans-serif" },
  { label: "Sora", value: "Sora, sans-serif" },
  { label: "Verdana", value: "Verdana, sans-serif" },
  { label: "Arial", value: "Arial, sans-serif" },
  { label: "Helvetica", value: "Helvetica, sans-serif" },
  { label: "Tahoma", value: "Tahoma, sans-serif" },
  { label: "Playfair Display", value: "'Playfair Display', serif" },
  { label: "Lora", value: "Lora, serif" },
  { label: "Fraunces", value: "Fraunces, serif" },
  { label: "Cinzel", value: "Cinzel, serif" },
  { label: "Merriweather", value: "Merriweather, serif" },
  { label: "DM Serif Display", value: "'DM Serif Display', serif" },
  { label: "Cormorant Garamond", value: "'Cormorant Garamond', serif" },
  { label: "Libre Baskerville", value: "Libre Baskerville, serif" },
  { label: "Georgia", value: "Georgia, serif" },
  { label: "Times New Roman", value: "'Times New Roman', serif" },
  { label: "JetBrains Mono", value: "'JetBrains Mono', monospace" },
  { label: "Fira Code", value: "'Fira Code', monospace" },
  { label: "Space Mono", value: "'Space Mono', monospace" },
  { label: "IBM Plex Mono", value: "'IBM Plex Mono', monospace" },
  { label: "Courier New", value: "'Courier New', monospace" },
  { label: "Pacifico", value: "Pacifico, cursive" },
  { label: "Lobster", value: "Lobster, cursive" },
  { label: "Righteous", value: "Righteous, cursive" },
  { label: "Caveat", value: "Caveat, cursive" },
  { label: "Bangers", value: "Bangers, cursive" },
  { label: "Bebas Neue", value: "'Bebas Neue', sans-serif" },
  { label: "Abril Fatface", value: "'Abril Fatface', serif" },
  { label: "Yeseva One", value: "'Yeseva One', serif" },
];

export const FONT_SIZES = [
  "1px",
  "2px",
  "4px",
  "6px",
  "8px",
  "10px",
  "11px",
  "12px",
  "13px",
  "14px",
  "15px",
  "16px",
  "18px",
  "20px",
  "22px",
  "24px",
  "28px",
  "32px",
  "36px",
  "40px",
  "48px",
  "56px",
  "64px",
  "72px",
  "96px",
];
